PythonVersion="3.9.7"
packagedir=".python_packages/lib/site-packages"
OperationId="|dIJ/KIyPTGs=.41d496b6_"
SourceDirectoryInBuildContainer="/tmp/zipdeploy/extracted"
PlatformName="python"
CompressDestinationDir="false"
